// <auto-generated />
namespace Landeeyo.Pizza.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class LogModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LogModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201405011410220_LogModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
