// <auto-generated />
namespace Landeeyo.Pizza.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class KeysOnUserModelModified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KeysOnUserModelModified));
        
        string IMigrationMetadata.Id
        {
            get { return "201405011216298_KeysOnUserModelModified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
